### ISSUE TITLE
uncommon intervalsShorthands

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#11]
#### Description
intervalsShorthands define is uncommon in  **./src/modules/music.js**, the flat sign should be written before the note 

**ref**
https://en.wikipedia.org/wiki/List_of_musical_scales_and_modes

#### Implementation details

```
export const intervalsShorthands = [
	'R',
	'♭2',
	'2',
	'♭3',
	'3',
	'4',
	'♭5',
	'5',
	'♭6',
	'6',
	'♭7',
	'7',
];
```

**Comment by cheap-glitch** [comment]
I agree, this has been fixed on the develop branch.
