### ISSUE TITLE
abbreviation of intervalsNames 

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#12]
#### Description

care to have abbreviation of interval name (m3 for Minor third, M3 for Major third, P4 for Perfect fourth, etc) in ./src/modules/music.js

**ref**
https://en.wikipedia.org/wiki/Interval_(music)#Main_intervals

#### Implementation details

**./src/modules/music.js**
```
export const intervalsNames = [
	'Root (R)',
	'Minor second (m2)',
	'Major second (M2)',
	'Minor third (m3)',
	'Major third (M3)',
	'Perfect fourth (P4)',
	'Diminished fifth (d5)',
	'Perfect fifth (P5)',
	'Minor sixth (m6)',
	'Major sixth (M6)',
	'Minor seventh (m7)',
	'Major seventh (M7)',
];
```

**./src/components/FretboardSequencesItemInterval.vue**
`		p.tooltip__text Highlight {{ name }} notes`

remove lowercase() function because m3 (Minor third) is different with M3 (Major third)

thanks

**Comment by cheap-glitch** [comment]
I don't really see the use of this. Can you give a concrete example where this would prove useful?

**Comment by sugizo** [comment]
it's just user behaviour conviniently read the interval on music (semitone, degree, interval short, interval name, etc), it's all about synonim

think nice to have 'display interval' on fretboarder to show that P4, P5, etc
while the b3, b5 is rename into degree, since it's called degree on music

**ref that use interval name on fretboard**
https://hidechae.github.io/gt-scale
