### ISSUE TITLE
export jpg and png

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#14]
#### Description

export to jpg and png in **./src/modules/export.js** seems unfinished yet

#### Implementation details

export to jpg and png should provide a file with it's selected format, thanks

**Comment by cheap-glitch** [comment]
Thank you for the bug report!

The cause is the CSP header that's preventing the image blob from being loaded by the browser. I pushed a fix on the develop branch, this should be resolved when the new version is deployed.

**Comment by cheap-glitch** [comment]
Tested in Firefox and Chromium, works again.
