### ISSUE TITLE
@vue/composition-api dependency not found

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#20]
#### Environment

 * Operating system:
Darwin
 * Browser name and version:
Chrome Version 85.0.4183.83 (Official Build) (64-bit)

#### Description

on terminal when execute 
`npm run serve`

```
This dependency was not found:

* @vue/composition-api in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/VTextSelect.vue?vue&type=script&lang=js&, ./src/hooks/useSelectedOptionLabel.js
```

#### Steps to reproduce

```
git clone https://github.com/cheap-glitch/fretboarder
cd fretboarder
npm install
npm run serve
```

#### Possible solutions

`npm install --save @vue/composition-api`
or
add 
`"@vue/composition-api": "^1.0.0-beta.14",`
in **./package.json**

thanks

**Comment by cheap-glitch** [comment]
This is not a bug, `@vue/composition-api` was removed on purpose. Make sure you're up to date with the `develop` branch by running `git pull origin develop` (assuming you named the remote `origin`).
