### ISSUE TITLE
group the scale into it's mode

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#21]
#### Description

better to group the scale into it's mode to make guitarist realize the relation between the scale and it's mode on **./src/components/FretboardSequencesItem.vue**

#### Implementation details

already send https://github.com/cheap-glitch/fretboarder/pull/17 before with the scale and it's mode (group it, and separate with carriage return)

#### Examples

this is how to group the scale with it's mode in music theory, as you can see the interval pattern is modified by the sequence (just one interval moving from first into last)

![Hexatonic Scale](https://user-images.githubusercontent.com/2418295/93807908-7dca3b00-fc75-11ea-9a7a-446f882a9b9a.png)

can send the full image of it's if you want or the PR about that
thanks

**Comment by cheap-glitch** [comment]
I tried to order the scales and arpeggios from more to less "useful", i.e. the most used scales first and the ones seldom used last.

But it's true that this order is completely arbitrary and other musicians might not agree on it. Maybe ordering by mode would be better.

Can you send the full image so I can see what that would look like?

**Comment by sugizo** [comment]
like your idea to separate the scale, the most 'used scale & arpeggio' by guitarist, because sometime guitarist have no idea, which scale is mostly used by most guitarist, and they can use it as a base scale 

**suggestion** 
- grouping 'most used scale' < 10 or < 5 scales, e.g. ionian, aeolian, major pentatonic, minor pentatonic
- then grouping scale and it's mode

with this idea, seems will be redundant scale defined on html select tag, but, no worries, just duplicate < 10 or < 5 scales wont hurt

**note about 'most used scale'**
better to input the standard scale that not related with some genre or etnic, e.g. blues major, blues minor or bebop (most usedly in jazz), gypsy scale, oriental scale, etc

same idea for arpeggio, but as you can predict, it will goes to 'triad chord arpeggio' plus some 'seventh (major or dominant)' on the 'most used arpeggio'

your choice

attached interval sequence to determine relationship between scales and it's mode
seems incomplete, e.g. in scale (hirajoshi, iwato), bebop scale 
but wont add from unknown resources, everything taken from wiki (link provided below)

[Interval Sequences.pdf](https://github.com/cheap-glitch/fretboarder/files/5260994/Interval.Sequences.pdf)


**ref**
https://en.wikipedia.org/wiki/List_of_musical_scales_and_modes

thanks

**Comment by cheap-glitch** [comment]
> **suggestion** 
> - grouping 'most used scale' < 10 or < 5 scales, e.g. ionian, aeolian, major pentatonic, minor pentatonic
> - then grouping scale and it's mode

That's pretty much what I did, see 2edde5cc6b2cd78a079aa6c21f764948934677b9.

I think I'll reorder the scales to match the "progression" of each mode, it's what makes the most sense. Thank you for the full scale table, it's very convenient!
