### ISSUE TITLE
Vuex-plugin-save-state does not exist

### ISSUE THREAD

**Issue by ted537** [cheap-glitch/fretboarder#29]
### Environment

 * Operating system: Ubuntu 22
 * Browser name and version: N/A

### Description

`npm install` fails with the following error.

```
ted@ted-MS-7817:~/git/fretboarder$ npm i --legacy-peer-deps
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vuex-plugin-save-state/-/vuex-plugin-save-state-2.0.0.tgz - Not found
npm ERR! 404 
npm ERR! 404  'vuex-plugin-save-state@https://registry.npmjs.org/vuex-plugin-save-state/-/vuex-plugin-save-state-2.0.0.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

### Steps to reproduce

1. `npm install`

### Possible solutions

Seems to be a small library. Was it renamed? Or just deleted off the face of the earth?

**Comment by ted537** [comment]
Similar story for  "@cheap-glitch/scss-mixins", "@cheap-glitch/scss-reset", and "@chea--glitch/vue-clie-plugin-fontawesome".

**Comment by cheap-glitch** [comment]
Yep, those are old libs of mine that I abandoned and removed from npm a while ago.

One day™ I'll rewrite this project using TypeScript and Vue 3… But in the meantime it should be considered as unmaintained.
