### ISSUE TITLE
vue missing dependacies

### ISSUE THREAD

**Issue by jdesl** [cheap-glitch/fretboarder#31]
Hello,

I was building the same application in some python flask & svg. But this looks much better.
I know nothing about vue & vuex. Trying to run the modules installer i'm missing these dependancies: 

"vuex-plugin-save-state": "^2.0.0",
"@cheap-glitch/scss-mixins": "^1.0.1",
"@cheap-glitch/scss-reset": "^1.0.1",
"@cheap-glitch/stylelint-config-properties-order": "^1.0.0",
"@cheap-glitch/vue-cli-plugin-fontawesome": "^1.0.9",

Any tips where I can find these?

**Comment by pouyaSamie** [comment]
seems like cheap-glitch/* are his private repos.

**Comment by meeksba** [comment]
@jdesl Were you able to resolve this? I'm running into the same issue as well when trying to build this application.

**Comment by Kernix13** [comment]
> I was building the same application in some python flask & svg. But this looks much better. I know nothing about vue & vuex. Trying to run the modules installer i'm missing these dependencies:

Did you run `npm install`? I would assume you did but something must have gone wrong. You should try uninstalling everything and then run `npm install` again and look in the console/terminal for error messages for those packages. Or else install each of those packages manually.
