### ISSUE TITLE
SyntaxError: Unexpected token { on cli-engine.js:406

### ISSUE THREAD

**Issue by sugizo** [cheap-glitch/fretboarder#7]
#### Environment

 * Operating system:
Darwin
 * Browser name and version:
Chrome Version 85.0.4183.83 (Official Build) (64-bit)

#### Description
 ```
ERROR  Failed to compile with 1 errors                                 07:42:27

 error  in ./src/main.js

Syntax Error: /Users/sugizo/Downloads/learn/fretboarder/node_modules/eslint/lib/cli-engine/cli-engine.js:406
    } catch {
            ^

SyntaxError: Unexpected token {


 @ multi (webpack)-dev-server/client?https://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/main.js
```

#### Steps to reproduce

```
git clone https://github.com/cheap-glitch/fretboarder
cd fretboarder
npm install
npm run serve
```

https://fretboarder.app wonderful piece of arts, helpful to widen guitarist knowledge about scale, arpeggio and it's variation feature
thanks

**Comment by cheap-glitch** [comment]
Hi,
first of all, thanks for your bug report!

As you can see in this line:
```
Syntax Error: /Users/sugizo/Downloads/learn/fretboarder/node_modules/eslint/lib/cli-engine/cli-engine.js:406
```
the error doesn't originate from Fretboarder but from one of its indirect dependencies (`eslint` in this case).
My guess is that you're running an old version of Node that doesn't support [optional `catch` binding](https://github.com/tc39/proposal-optional-catch-binding).

You should update Node to the latest stable version (`v14.10.1` at this time) to avoid this kind of problems. If you can't, at least upgrade to `v10.3.0` (https://node.green/#ES2019-misc-optional-catch-binding). You can see the version of Node you're running with `node -v`.

> fretboarder.app wonderful piece of arts, helpful to widen guitarist knowledge about scale, arpeggio and it's variation feature

Thank you very much, I'm glad you find it useful!
